---
title: "Logistic_project_alec"
author: "Alec Pixton"
date: "2024-06-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| warning: FALSE
#| message: FALSE
library(tidymodels)
library(dplyr)
library(tidyverse)
library(yardstick)
library(patchwork)
library(discrim)
library(MASS)
library(ggcorrplot)
library(GGally)
```

```{r}
haiti <- read.csv("HaitiPixels.csv", sep=",", header=TRUE)
haiti$BT_class <- ifelse(haiti$Class == "Blue Tarp", TRUE, FALSE)
haiti$BT_class <- as.factor(haiti$BT_class)
haiti <- subset(haiti, select = -Class)
haiti_formula <- BT_class ~ .
```

```{r cache-prepare-LDA}

#| message: FALSE
#| warning: FALSE
#| cache: TRUE

folds <- vfold_cv(haiti, strata=BT_class)

haiti_logistic <- logistic_reg(mode="classification") %>% 
    set_engine("glm")
  
haiti_logistic_wf <- workflow() %>%
    add_model(haiti_logistic) %>%
    add_formula(haiti_formula)

haiti_logistic_fit_cv <- haiti_logistic_wf %>% 
    fit_resamples(folds, control=control_resamples(save_pred=TRUE))

haiti_logistic_cv_predictions <- collect_predictions(haiti_logistic_fit_cv)

haiti_logistic_cv_metrics <- collect_metrics(haiti_logistic_fit_cv)
haiti_logistic_cv_metrics
```
```{r}
haiti_logistic_roc <- haiti_logistic_cv_predictions %>%
  roc_curve(truth=BT_class, .pred_TRUE, event_level = "second") %>%
  ggplot(aes(x = 1-specificity, y = sensitivity)) + geom_line()
haiti_logistic_roc
```





```{r}
haiti_logistic_fit <- haiti_logistic_wf %>% fit(haiti)
```

```{r}
haiti_augment <- augment(haiti_logistic_fit, new_data=haiti)

performance_logistic <- probably::threshold_perf(haiti_augment, BT_class, .pred_TRUE, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(j_index, specificity, sensitivity, accuracy))

max_j_index_logistic <- performance_logistic %>% 
    filter(.metric == "j_index") %>% 
    filter(.estimate == max(.estimate))
max_j_index_logistic
```

```{r}
logistic_haiti <- logistic_reg(mode="classification") %>%
    set_engine("glm") %>%
    fit(haiti_formula, data=haiti)
haiti_augment <- augment(logistic_haiti, new_data=haiti)
names(haiti_augment)[2] <- ".predBlueTarp"

performance_haiti <- probably::threshold_perf(haiti_augment, BT_class, .predBlueTarp , 
                                        seq(0.00, 1.0, 0.1))
metrics_haiti <- pivot_wider(performance_haiti, id_cols=.threshold, names_from=.metric,
                       values_from=.estimate)
```
```{r}
roc_haiti <- roc_curve(haiti_augment, BT_class, .predBlueTarp) %>% 
    autoplot() +
    geom_point(data=metrics_haiti, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_haiti, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
```

```{r}
roc_haiti
```

