# DS 6030

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE)
knitr::opts_chunk$set(fig.align="center", fig.pos="tbh")
```

# Libraries and start cluster
```{r}
#| warning: FALSE
#| message: FALSE
library(tidymodels)
library(dplyr)
library(tidyverse)
library(yardstick)
library(patchwork)
library(discrim)
library(GGally)
library(doParallel)
cl <- makePSOCKcluster(parallel::detectCores(logical = FALSE))
registerDoParallel(cl)
```

# Read in data
```{r}
set.seed(4896)
haiti <- read.csv("HaitiPixels.csv", sep=",", header=TRUE)
haiti$BT_class <- ifelse(haiti$Class == "Blue Tarp", TRUE, FALSE)
haiti$BT_class <- as.factor(haiti$BT_class)
summary(haiti)
#unique(haiti$Class)

```
# EDA graph
```{r}
frequency <- haiti %>% 
  count(Class)

ggplot(data=frequency, aes(x=Class, y=n, fill=Class)) + 
  geom_bar(stat = "identity")+
  labs(title="Distribution of Classes",
       x="Class",
       y="Count") +
  scale_y_continuous(labels = scales::comma)+
  theme_minimal()+
  geom_text(aes(label = scales::comma(n)), size=4, vjust = 1) +
  scale_fill_manual(values = c( "Blue Tarp" = "blue",
                                "Rooftop" = "red", 
                                "Vegetation" = "green",
                                "Soil" = "orange",
                                "Various Non Tarp" = "gray"))+ 
  guides(fill = FALSE)

```

```{r}
ggpairs(haiti, columns = 2:4, aes(color=BT_class, alpha=.8)) +
  theme_minimal()
```

# Create formula
```{r}
haiti <- subset(haiti, select = -Class)
haiti_formula <- BT_class ~ .

```

# Training cross-validation
```{r cache-prepare-LDA}

#| message: FALSE
#| warning: FALSE
#| cache: TRUE

folds <- vfold_cv(haiti, strata=BT_class)

haiti_LDA <- discrim_linear(mode="classification") %>% 
    set_engine("MASS")
  
haiti_LDA_wf <- workflow() %>%
    add_model(haiti_LDA) %>%
    add_formula(haiti_formula)

haiti_LDA_fit_cv <- haiti_LDA_wf %>% 
    fit_resamples(folds, control=control_resamples(save_pred=TRUE))

haiti_LDA_cv_predictions <- collect_predictions(haiti_LDA_fit_cv)

haiti_LDA_cv_metrics <- collect_metrics(haiti_LDA_fit_cv)

haiti_LDA_cv_metrics
```


# Training performance and ROC curve
```{r}
library(yardstick)
haiti_LDA_fit <- haiti_LDA_wf %>% fit(haiti)

haiti_augment <- augment(haiti_LDA_fit, new_data=haiti)

performance_lda <- probably::threshold_perf(haiti_LDA_cv_predictions, BT_class, .pred_TRUE, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(j_index, yardstick::specificity, yardstick::sensitivity, accuracy, precision))

max_j_index_lda <- performance_lda %>% 
    filter(.metric == "j_index") %>% 
    filter(.estimate == max(.estimate))
max_j_index_lda

metrics_lda <- pivot_wider(performance_lda, id_cols=.threshold, names_from=.metric,
                       values_from=.estimate)
roc_haiti <- roc_curve(haiti_LDA_cv_predictions, BT_class, .pred_TRUE, event_level="second") %>% 
    autoplot() +
    geom_point(data=metrics_lda, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_lda, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
roc_haiti

```


# Get model performance metrics at optimal threshold on training data
```{r}

optimal_threshold <- max_j_index_lda[[1,1]]
optimal_threshold

metrics_training <- performance_lda %>% filter(.threshold == optimal_threshold)
metrics_training

lda_auc <- roc_auc(haiti_augment, BT_class, .pred_TRUE, event_level="second")
lda_auc

specificity <- metrics_training %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr <- 1-specificity
fpr
```

# Read in holdout data
```{r}
# ignoring "orthovnir067_ROI_Blue_Tarps_data.txt", and the .jpg files
# combining text files for holdout set & separating based on class

non_blue_files <- c("orthovnir057_ROI_NON_Blue_Tarps.txt", "orthovnir067_ROI_NOT_Blue_Tarps.txt", "orthovnir069_ROI_NOT_Blue_Tarps.txt", "orthovnir078_ROI_NON_Blue_Tarps.txt")
blue_files <- c("orthovnir067_ROI_Blue_Tarps.txt", "orthovnir069_ROI_Blue_Tarps.txt", "orthovnir078_ROI_Blue_Tarps.txt")


read_and_label <- function(files, label) {
  map_df(files, function(file) {
    data <- read_lines(file, skip = 8)  # Skip metadata
    
    df <- read.table(text = data, header = FALSE, stringsAsFactors = FALSE, fill = TRUE)
   
    df <- df %>% mutate(class = label)
  
    colnames(df) <- c("ID", "X", "Y", "Map_X", "Map_Y", "Lat", "Lon", "B1", "B2", "B3", "BT_class")
    return(df)
  })
}


non_blue_df <- read_and_label(non_blue_files, "FALSE")
blue_df <- read_and_label(blue_files, "TRUE")


Haiti_holdout <- bind_rows(non_blue_df, blue_df)

Haiti_holdout$BT_class <- as.factor(Haiti_holdout$BT_class)

```

# Assign B1, B2, B3 variables in holdout set to Red, Green, and Blue
```{r}
### Can classify holdout colors based on this method.

averages_train <- haiti %>%
  group_by(BT_class) %>%
  summarise(
    avg_Red = mean(Red, na.rm = TRUE),
    avg_Green = mean(Green, na.rm = TRUE),
    avg_Blue = mean(Blue, na.rm = TRUE)
  )

print(averages_train)

averages_holdout <- Haiti_holdout %>%
  group_by(BT_class) %>%
  summarise(
    avg_B1 = mean(B1, na.rm = TRUE),
    avg_B2 = mean(B2, na.rm = TRUE),
    avg_B3 = mean(B3, na.rm = TRUE)
  )

print(averages_holdout)

Haiti_holdout <- Haiti_holdout %>%
  rename(Red = B1,
         Green = B2,
         Blue = B3)

Haiti_holdout <- Haiti_holdout %>%
  dplyr::select(Red, Green, Blue, BT_class)
```
# Holdout data metrics
```{r}
haiti_augment_test <- augment(haiti_LDA_fit, new_data=Haiti_holdout)

performance_lda_test <- probably::threshold_perf(haiti_augment_test, BT_class, .pred_TRUE, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(j_index, yardstick::specificity, yardstick::sensitivity, accuracy, precision))

metrics_test <- performance_lda_test %>% filter(.threshold == optimal_threshold)
metrics_test

lda_auc <- roc_auc(haiti_augment_test, BT_class, .pred_TRUE, event_level="second")
lda_auc

specificity_test <- metrics_test %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr_test <- 1-specificity_test
fpr_test

roc_haiti_test <- roc_curve(haiti_augment_test, BT_class, .pred_TRUE, event_level="second") %>% 
    autoplot() +
    geom_point(data=metrics_test, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_test, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
roc_haiti_test
```

# End cluster
```{r}
stopCluster(cl)
registerDoSEQ()
```

# Logistic Start

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| warning: FALSE
#| message: FALSE
library(tidymodels)
library(dplyr)
library(tidyverse)
library(yardstick)
library(patchwork)
library(discrim)
library(MASS)
library(ggcorrplot)
library(GGally)
```

```{r}
set.seed(4896)
haiti <- read.csv("HaitiPixels.csv", sep=",", header=TRUE)
haiti$BT_class <- ifelse(haiti$Class == "Blue Tarp", TRUE, FALSE)
haiti$BT_class <- as.factor(haiti$BT_class)
haiti <- subset(haiti, select = -Class)
haiti_formula <- BT_class ~ .
```

```{r cache-prepare-LDA}

#| message: FALSE
#| warning: FALSE
#| cache: TRUE

folds <- vfold_cv(haiti, strata=BT_class)

haiti_logistic <- logistic_reg(mode="classification") %>% 
    set_engine("glm")
  
haiti_logistic_wf <- workflow() %>%
    add_model(haiti_logistic) %>%
    add_formula(haiti_formula)

haiti_logistic_fit_cv <- haiti_logistic_wf %>% 
    fit_resamples(folds, control=control_resamples(save_pred=TRUE))

haiti_logistic_cv_predictions <- collect_predictions(haiti_logistic_fit_cv)

haiti_logistic_cv_metrics <- collect_metrics(haiti_logistic_fit_cv)
haiti_logistic_cv_metrics
```



```{r}
performance_logistic <- probably::threshold_perf(haiti_logistic_cv_predictions, BT_class, .pred_TRUE, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(j_index, yardstick::specificity, yardstick::sensitivity, accuracy, precision))

max_j_index_logistic <- performance_logistic %>% 
    filter(.metric == "j_index") %>% 
    filter(.estimate == max(.estimate))
max_j_index_logistic
```


```{r}
metrics_logistic <- pivot_wider(performance_logistic, id_cols=.threshold, names_from=.metric,
                       values_from=.estimate)
```
```{r}
roc_logistic <- roc_curve(haiti_logistic_cv_predictions, BT_class, .pred_TRUE, event_level = "second") %>% 
    autoplot() +
    geom_point(data=metrics_logistic, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_logistic, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
```

```{r}
roc_logistic
```

```{r}
optimal_threshold_logistic <- max_j_index_logistic[[1,1]]
optimal_threshold_logistic
```
```{r}
metrics_training_logistic <- performance_logistic %>% filter(.threshold == optimal_threshold_logistic)
metrics_training_logistic
```
```{r}
haiti_logistic_fit <- haiti_logistic_wf %>% fit(haiti)
haiti_augment <- augment(haiti_logistic_fit, new_data=haiti)
logistic_auc <- roc_auc(haiti_augment, BT_class, .pred_TRUE, event_level="second")
logistic_auc
```

```{r}
specificity <- metrics_training_logistic %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr <- 1-specificity
fpr
```

```{r}
# ignoring "orthovnir067_ROI_Blue_Tarps_data.txt", and the .jpg files
# combining text files for holdout set & separating based on class

non_blue_files <- c("orthovnir057_ROI_NON_Blue_Tarps.txt", "orthovnir067_ROI_NOT_Blue_Tarps.txt", "orthovnir069_ROI_NOT_Blue_Tarps.txt", "orthovnir078_ROI_NON_Blue_Tarps.txt")
blue_files <- c("orthovnir067_ROI_Blue_Tarps.txt", "orthovnir069_ROI_Blue_Tarps.txt", "orthovnir078_ROI_Blue_Tarps.txt")


read_and_label <- function(files, label) {
  map_df(files, function(file) {
    data <- read_lines(file, skip = 8)  # Skip metadata
    
    df <- read.table(text = data, header = FALSE, stringsAsFactors = FALSE, fill = TRUE)
   
    df <- df %>% mutate(class = label)
  
    colnames(df) <- c("ID", "X", "Y", "Map_X", "Map_Y", "Lat", "Lon", "B1", "B2", "B3", "BT_class")
    return(df)
  })
}


non_blue_df <- read_and_label(non_blue_files, "FALSE")
blue_df <- read_and_label(blue_files, "TRUE")


Haiti_holdout <- bind_rows(non_blue_df, blue_df)

Haiti_holdout$BT_class <- as.factor(Haiti_holdout$BT_class)

```

```{r}
Haiti_holdout <- Haiti_holdout %>%
  rename(Red = B1,
         Green = B2,
         Blue = B3)

Haiti_holdout <- Haiti_holdout %>%
  dplyr::select(Red, Green, Blue, BT_class)
```

```{r}
haiti_augment_test <- augment(haiti_logistic_fit, new_data=Haiti_holdout)

performance_logistic_test <- probably::threshold_perf(haiti_augment_test, BT_class, .pred_TRUE, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(j_index, yardstick::specificity, yardstick::sensitivity, accuracy, precision))

metrics_test_logistic <- performance_logistic_test %>% filter(.threshold == optimal_threshold_logistic)
metrics_test_logistic

logisitc_auc <- roc_auc(haiti_augment_test, BT_class, .pred_TRUE, event_level="second")
logistic_auc

specificity_test_logistic <- metrics_test_logistic %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr_test_logistic <- 1-specificity_test_logistic
fpr_test_logistic
```
```{r}
roc_logistic_test <- roc_curve(haiti_augment_test, BT_class, .pred_TRUE, event_level = "second") %>% 
    autoplot() +
    geom_point(data=metrics_logistic, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_logistic, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
roc_logistic_test
```

# QDA Start

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
library(ggcorrplot)
library(patchwork)
library(tidymodels)
library(GGally)
library(htmlTable)
library(ROCR)
library(knitr)
library(caret)
library(plotly)
library(gridExtra)
library(discrim)
```

```{r}
Haiti<-read.csv("HaitiPixels.csv")
Haiti$BlueTarp <- ifelse(Haiti$Class == "Blue Tarp", "Yes", "No")
Haiti$BlueTarp <- factor(Haiti$BlueTarp, levels = c("No", "Yes"))
```

```{r}
summary(Haiti)
```

```{r}
unique(Haiti$Class)
```

```{r}
frequency <- Haiti %>% 
  count(Class)

ggplot(data=frequency, aes(x=Class, y=n, fill=Class)) + 
  geom_bar(stat = "identity")+
  labs(title="Dist. of Classes",
       x="Class",
       y="Count") +
  scale_y_continuous(labels = scales::comma)+
  theme_minimal()+
  geom_text(aes(label = scales::comma(n)), size=4, vjust = 1) +
  scale_fill_manual(values = c( "Blue Tarp" = "blue",
                                "Rooftop" = "red", 
                                "Vegetation" = "green",
                                "Soil" = "orange",
                                "Various Non Tarp" = "gray"))+ 
  guides(fill = FALSE)

```
```{r}
ggpairs(Haiti, columns = 2:4, aes(color=BlueTarp, alpha=.8)) +
  theme_minimal()
```

```{r}
# ignoring "orthovnir067_ROI_Blue_Tarps_data.txt", and the .jpg files
# combining text files for holdout set & separating based on class

non_blue_files <- c("orthovnir057_ROI_NON_Blue_Tarps.txt", "orthovnir067_ROI_NOT_Blue_Tarps.txt", "orthovnir069_ROI_NOT_Blue_Tarps.txt", "orthovnir078_ROI_NON_Blue_Tarps.txt")
blue_files <- c("orthovnir067_ROI_Blue_Tarps.txt", "orthovnir069_ROI_Blue_Tarps.txt", "orthovnir078_ROI_Blue_Tarps.txt")

read_and_label <- function(files, label) {
  map_df(files, function(file) {
    data <- read_lines(file, skip = 8)  # Skip metadata
    
    df <- read.table(text = data, header = FALSE, stringsAsFactors = FALSE, fill = TRUE)
   
    df <- df %>% mutate(class = label)
  
    colnames(df) <- c("ID", "X", "Y", "Map_X", "Map_Y", "Lat", "Lon", "B1", "B2", "B3", "class")
    return(df)
  })
}

non_blue_df <- read_and_label(non_blue_files, "non-blue-tarp")
blue_df <- read_and_label(blue_files, "blue-tarp")

Haiti_holdout <- bind_rows(non_blue_df, blue_df)
Haiti_holdout$class <- as.factor(Haiti_holdout$class)
head(Haiti_holdout)
```

```{r}
u_seed <- 4896
formula <- BlueTarp ~ Red + Blue + Green
```

```{r}
set.seed(u_seed)

folds <- vfold_cv(Haiti, strata = "BlueTarp")

haiti_QDA <- discrim_quad(mode = "classification") %>%
  set_engine("MASS")

haiti_QDA_wf <- workflow() %>%
  add_model(haiti_QDA) %>%
  add_formula(formula)

haiti_QDA_fit_cv <- haiti_QDA_wf %>%
  fit_resamples(folds, control = control_resamples(save_pred = TRUE))

haiti_QDA_cv_predictions <- collect_predictions(haiti_QDA_fit_cv)
haiti_QDA_cv_metrics <- collect_metrics(haiti_QDA_fit_cv)

haiti_QDA_roc <- haiti_QDA_cv_predictions %>%
  roc_curve(truth = BlueTarp, .pred_Yes, event_level = "second") %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) + geom_line()

print(haiti_QDA_cv_metrics)
print(haiti_QDA_roc)
```
```{r}
library(yardstick)
haiti_QDA_fit <- haiti_QDA_wf %>% fit(Haiti)

haiti_augment <- augment(haiti_QDA_fit, new_data=Haiti)

performance_QDA <- probably::threshold_perf(haiti_QDA_cv_predictions, BlueTarp, .pred_Yes, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="second",
    metrics=metric_set(yardstick::j_index, yardstick::specificity, yardstick::sensitivity, yardstick::accuracy, yardstick::precision))

max_j_index_QDA <- performance_QDA %>% 
    filter(.metric == "j_index") %>% 
    filter(.estimate == max(.estimate))
max_j_index_QDA

metrics_QDA <- pivot_wider(performance_QDA, id_cols=.threshold, names_from=.metric,
                       values_from=.estimate)
roc_haiti <- roc_curve(haiti_QDA_cv_predictions, BlueTarp, .pred_Yes, event_level="second") %>% 
    autoplot() +
    geom_point(data=metrics_QDA, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_QDA, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
roc_haiti
```
```{r}
optimal_threshold <- max_j_index_QDA[[1,1]]
optimal_threshold

metrics_training <- performance_QDA %>% filter(.threshold == optimal_threshold)
metrics_training

QDA_auc <- roc_auc(haiti_augment, BlueTarp, .pred_Yes, event_level="second")
QDA_auc

specificity <- metrics_training %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr <- 1-specificity
fpr
```
```{r}
averages_train <- Haiti %>%
  group_by(BlueTarp) %>%
  summarise(
    avg_Red = mean(Red, na.rm = TRUE),
    avg_Green = mean(Green, na.rm = TRUE),
    avg_Blue = mean(Blue, na.rm = TRUE)
  )

print(averages_train)

averages_holdout <- Haiti_holdout %>%
  group_by(class) %>%
  summarise(
    avg_B1 = mean(B1, na.rm = TRUE),
    avg_B2 = mean(B2, na.rm = TRUE),
    avg_B3 = mean(B3, na.rm = TRUE)
  )

print(averages_holdout)

Haiti_holdout <- Haiti_holdout %>%
  rename(Red = B1,
         Green = B2,
         Blue = B3)

Haiti_holdout <- Haiti_holdout %>%
  dplyr::select(Red, Green, Blue, class)
```

```{r}
haiti_augment_test <- augment(haiti_QDA_fit, new_data=Haiti_holdout)

performance_QDA_test <- probably::threshold_perf(haiti_augment_test, class, .pred_Yes, 
    thresholds=seq(0.05, 0.95, 0.01), event_level="first",
    metrics=metric_set(yardstick::j_index, yardstick::specificity, yardstick::sensitivity, yardstick::accuracy, yardstick::precision))

metrics_test <- performance_QDA_test %>% filter(.threshold == optimal_threshold)
metrics_test

QDA_auc <- roc_auc(haiti_augment_test, class, .pred_Yes, event_level="first")
QDA_auc

specificity_test <- metrics_test %>% filter(.metric == "specificity") %>% pull(.estimate)
fpr_test <- 1-specificity_test
fpr_test

```
```{r}
metrics_wide <- metrics_test %>%
  pivot_wider(names_from = .metric, values_from = .estimate)

roc_haiti_test <- roc_curve(haiti_augment_test, class, .pred_Yes, event_level="first") %>% 
    autoplot() +
    geom_point(data=metrics_wide, aes(x=1-specificity, y=sensitivity), color='red') +
    geom_text(data=metrics_wide, aes(x=1-specificity, y=sensitivity, 
              label=.threshold), nudge_x=0.05, check_overlap=TRUE)
roc_haiti_test
```


